package threatintel

import (
	"context"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"sync/atomic"
	"testing"
	"time"
)

const sampleSpamhausDROP = `; Spamhaus DROP List 2026/01/01 - (c) 2026 The Spamhaus Project
; https://www.spamhaus.org/drop/drop.txt
;
1.10.16.0/20 ; SBL248995
1.32.128.0/18 ; SBL286275
5.42.92.0/24 ; SBL494136
; comment-only line, skip me
   ; indented comment
   45.227.255.0/24   ; trailing ws
not-an-ip-line
192.168.1.1 ; single ip, should become /32
2001:db8::/32 ; ipv6 cidr
`

func TestParse_HandlesSpamhausFormat(t *testing.T) {
	out, err := parse(strings.NewReader(sampleSpamhausDROP))
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	want := []string{
		"1.10.16.0/20",
		"1.32.128.0/18",
		"5.42.92.0/24",
		"45.227.255.0/24",
		"192.168.1.1/32",
		"2001:db8::/32",
	}
	if len(out) != len(want) {
		t.Fatalf("got %d entries, want %d: %v", len(out), len(want), out)
	}
	for i, w := range want {
		if out[i] != w {
			t.Errorf("entry %d = %q, want %q", i, out[i], w)
		}
	}
}

func TestParse_StripsTrailingMetadata(t *testing.T) {
	// FireHOL/some lists put extra cols after CIDR — we should keep only field 1.
	in := "10.0.0.0/24 firehol_level1 2024-01-01\n"
	out, err := parse(strings.NewReader(in))
	if err != nil || len(out) != 1 || out[0] != "10.0.0.0/24" {
		t.Fatalf("expected [10.0.0.0/24], got %v err=%v", out, err)
	}
}

func TestParse_RejectsGarbage(t *testing.T) {
	in := "###\nnot-a-cidr\n   \n999.999.999.999\n"
	out, _ := parse(strings.NewReader(in))
	if len(out) != 0 {
		t.Fatalf("expected 0 entries from garbage, got %v", out)
	}
}

type fakeReloader struct{ calls atomic.Int32 }

func (f *fakeReloader) Reload() error { f.calls.Add(1); return nil }

func TestManager_FetchWritesFileAndReloads(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "text/plain")
		_, _ = w.Write([]byte(sampleSpamhausDROP))
	}))
	defer srv.Close()

	tmp := t.TempDir()
	out := filepath.Join(tmp, "threatintel.data")
	rl := &fakeReloader{}
	m := NewManager(Config{
		Enabled:    true,
		URLs:       []string{srv.URL},
		OutputPath: out,
		Refresh:    0, // one-shot
		Timeout:    3 * time.Second,
	}, rl)

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	m.Start(ctx)

	st := m.Status()
	if st.LastError != "" {
		t.Fatalf("unexpected error: %s", st.LastError)
	}
	if st.EntryCount != 6 {
		t.Errorf("entry count = %d, want 6", st.EntryCount)
	}
	if st.LastSync.IsZero() {
		t.Error("LastSync was not set")
	}
	if rl.calls.Load() != 1 {
		t.Errorf("Reload called %d times, want 1", rl.calls.Load())
	}
	body, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("read output: %v", err)
	}
	got := string(body)
	if !strings.Contains(got, "1.10.16.0/20") || !strings.Contains(got, "2001:db8::/32") {
		t.Errorf("output missing expected entries:\n%s", got)
	}
	if !strings.HasPrefix(got, "# generated by latentguard threatintel") {
		t.Errorf("output missing generator comment header, got first line: %q",
			strings.SplitN(got, "\n", 2)[0])
	}
}

func TestManager_DisabledIsNoop(t *testing.T) {
	rl := &fakeReloader{}
	m := NewManager(Config{Enabled: false, URLs: []string{"http://nowhere.invalid/x"}}, rl)
	m.Start(context.Background())
	if rl.calls.Load() != 0 {
		t.Errorf("Reload called %d times on disabled manager, want 0", rl.calls.Load())
	}
}

func TestManager_FailSoftOnSourceDown(t *testing.T) {
	rl := &fakeReloader{}
	m := NewManager(Config{
		Enabled:    true,
		URLs:       []string{"http://127.0.0.1:1/never"},
		OutputPath: filepath.Join(t.TempDir(), "x.data"),
		Timeout:    200 * time.Millisecond,
	}, rl)
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()
	m.Start(ctx) // must not panic; must record error
	st := m.Status()
	if st.LastError == "" {
		t.Error("expected LastError on unreachable source")
	}
	if rl.calls.Load() != 0 {
		t.Errorf("Reload should not be called when fetch fails, got %d", rl.calls.Load())
	}
}
