// Package threatintel pulls IP blocklists from public sources (Spamhaus DROP
// / EDROP, FireHOL, anything serving CIDR-per-line plain text) and writes
// them to a Coraza @ipMatchFromFile data file. A separate goroutine in
// cmd/proxy/main.go calls Fetch periodically and then asks the WAF engine to
// hot-reload, so newly-blocklisted IPs land in the deny chain without a
// proxy restart.
//
// Format expected on the wire:
//   - one CIDR or single IPv4/IPv6 per line
//   - ';' or '#' starts a comment (rest of line ignored)
//   - blank lines ignored
//   - Spamhaus uses '193.108.155.0/24 ; SBL232605' which both rules handle
//
// Format written for Coraza:
//   - one CIDR per line, no comments, no blank lines
//   - first line is a comment '# generated by latentguard threatintel ...'
//     which @ipMatchFromFile silently ignores (lines starting with '#')
package threatintel

import (
	"bufio"
	"context"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"
)

// EnsurePlaceholder writes a non-empty comment-only file at path if nothing
// exists there. Call this BEFORE coraza.New() so the @ipMatchFromFile rule
// can parse cleanly on a fresh clone where the fetcher hasn't run yet.
// Atomic via the same temp-file + rename dance as writeAtomic.
func EnsurePlaceholder(path string) error {
	if path == "" {
		return errors.New("EnsurePlaceholder: path empty")
	}
	if _, err := os.Stat(path); err == nil {
		return nil // already present, leave whatever's there alone
	} else if !os.IsNotExist(err) {
		return err
	}
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", dir, err)
	}
	tmp, err := os.CreateTemp(dir, ".threatintel-init-*.tmp")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name())
	_, _ = tmp.WriteString("# placeholder -- populated at runtime by latentguard threatintel\n")
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), path)
}

// Status is the snapshot a /__threatintel handler reports. All fields are
// safe to read after Manager.Status() returns a copy.
type Status struct {
	Enabled     bool      `json:"enabled"`
	Sources     []string  `json:"sources"`
	OutputPath  string    `json:"output_path"`
	LastSync    time.Time `json:"last_sync"`
	LastError   string    `json:"last_error,omitempty"`
	EntryCount  int       `json:"entry_count"`
	BytesWriten int       `json:"bytes_written"`
}

// Reloader is whatever the proxy hands us so we can swap in a fresh ruleset
// after rewriting the data file. coraza.Engine satisfies this.
type Reloader interface {
	Reload() error
}

// Manager owns the periodic fetch loop, the data file on disk, and the
// status snapshot. One instance per process.
type Manager struct {
	cfg      Config
	reloader Reloader

	mu     sync.RWMutex
	status Status
	client *http.Client
}

// Config is loaded from env vars in cmd/proxy/main.go. URLs is a comma-split
// list; multiple sources get fetched in order and merged (later sources
// extend earlier ones — duplicates de-duped).
type Config struct {
	Enabled    bool
	URLs       []string
	OutputPath string        // absolute path of the .data file Coraza reads
	Refresh    time.Duration // 0 disables the ticker (one-shot mode)
	Timeout    time.Duration // per-source HTTP timeout
}

// NewManager wires up but does NOT start the loop. Call Start() after the
// proxy is up; the boot fetch runs synchronously inside Start so the first
// request the proxy serves already enforces today's list.
func NewManager(cfg Config, reloader Reloader) *Manager {
	if cfg.Timeout == 0 {
		cfg.Timeout = 15 * time.Second
	}
	return &Manager{
		cfg:      cfg,
		reloader: reloader,
		client:   &http.Client{Timeout: cfg.Timeout},
		status: Status{
			Enabled:    cfg.Enabled,
			Sources:    append([]string(nil), cfg.URLs...),
			OutputPath: cfg.OutputPath,
		},
	}
}

// Start runs one synchronous fetch+reload, then (if cfg.Refresh > 0) spawns a
// ticker goroutine that repeats forever. The boot fetch is fail-soft: a
// network failure logs a warning, leaves any existing data file untouched,
// and the proxy keeps serving (it just won't have today's blocklist).
func (m *Manager) Start(ctx context.Context) {
	if !m.cfg.Enabled {
		return
	}
	if err := m.runOnce(ctx); err != nil {
		// Don't fail boot — we'd rather have a proxy without threat-intel
		// than no proxy at all. Status carries the error for ops visibility.
		fmt.Fprintf(os.Stderr, "threatintel: initial fetch failed: %v\n", err)
	}
	if m.cfg.Refresh <= 0 {
		return
	}
	go func() {
		ticker := time.NewTicker(m.cfg.Refresh)
		defer ticker.Stop()
		for {
			select {
			case <-ctx.Done():
				return
			case <-ticker.C:
				if err := m.runOnce(ctx); err != nil {
					fmt.Fprintf(os.Stderr, "threatintel: refresh failed: %v\n", err)
				}
			}
		}
	}()
}

func (m *Manager) runOnce(ctx context.Context) error {
	cidrs, err := m.fetchAll(ctx)
	if err != nil {
		m.setError(err)
		return err
	}
	n, written, err := m.writeAtomic(cidrs)
	if err != nil {
		m.setError(err)
		return err
	}
	if m.reloader != nil {
		if err := m.reloader.Reload(); err != nil {
			m.setError(fmt.Errorf("waf reload: %w", err))
			return err
		}
	}
	m.setOK(n, written)
	return nil
}

// Status returns a snapshot. Cheap, mutex-protected; safe to call from
// HTTP handlers in the hot path.
func (m *Manager) Status() Status {
	m.mu.RLock()
	defer m.mu.RUnlock()
	s := m.status
	s.Sources = append([]string(nil), s.Sources...)
	return s
}

func (m *Manager) setOK(entries, bytes int) {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.status.LastSync = time.Now().UTC()
	m.status.LastError = ""
	m.status.EntryCount = entries
	m.status.BytesWriten = bytes
}

func (m *Manager) setError(err error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.status.LastError = err.Error()
}

func (m *Manager) fetchAll(ctx context.Context) ([]string, error) {
	seen := make(map[string]struct{})
	var ordered []string
	var firstErr error
	for _, u := range m.cfg.URLs {
		cidrs, err := m.fetchOne(ctx, u)
		if err != nil {
			if firstErr == nil {
				firstErr = fmt.Errorf("%s: %w", u, err)
			}
			continue
		}
		for _, c := range cidrs {
			if _, ok := seen[c]; ok {
				continue
			}
			seen[c] = struct{}{}
			ordered = append(ordered, c)
		}
	}
	if len(ordered) == 0 && firstErr != nil {
		return nil, firstErr
	}
	return ordered, nil
}

func (m *Manager) fetchOne(ctx context.Context, url string) ([]string, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("User-Agent", "LatentGuard-ThreatIntel/1.0")
	req.Header.Set("Accept", "text/plain")
	resp, err := m.client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		// Drain a little to be friendly to the connection pool.
		_, _ = io.CopyN(io.Discard, resp.Body, 1024)
		return nil, fmt.Errorf("http %d", resp.StatusCode)
	}
	return parse(resp.Body)
}

// parse reads a Spamhaus-style stream: CIDR or IP per line, ';' or '#'
// introduces a comment, blanks ignored. Validates each entry as a parseable
// CIDR or IP (single IPs get '/32' or '/128' appended so Coraza always sees
// CIDR notation -- @ipMatchFromFile accepts both but uniformity helps
// debugging).
func parse(r io.Reader) ([]string, error) {
	var out []string
	scanner := bufio.NewScanner(r)
	scanner.Buffer(make([]byte, 1<<16), 1<<20)
	for scanner.Scan() {
		line := scanner.Text()
		if i := strings.IndexAny(line, ";#"); i >= 0 {
			line = line[:i]
		}
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		// First field only — some lists put extra metadata after the CIDR.
		if sp := strings.IndexAny(line, " \t"); sp > 0 {
			line = line[:sp]
		}
		if c, ok := normalize(line); ok {
			out = append(out, c)
		}
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	return out, nil
}

// normalize returns canonical CIDR form ("a.b.c.d/m") or false if the line
// doesn't look like an IP/CIDR. Single IPs become /32 (v4) or /128 (v6).
func normalize(s string) (string, bool) {
	if strings.Contains(s, "/") {
		_, ipnet, err := net.ParseCIDR(s)
		if err != nil {
			return "", false
		}
		return ipnet.String(), true
	}
	ip := net.ParseIP(s)
	if ip == nil {
		return "", false
	}
	if ip.To4() != nil {
		return ip.String() + "/32", true
	}
	return ip.String() + "/128", true
}

// writeAtomic dumps cidrs to a sibling temp file in the output dir then
// renames over the target. On most filesystems rename is atomic so the
// goroutine that called Reload() never sees a half-written file.
func (m *Manager) writeAtomic(cidrs []string) (int, int, error) {
	if m.cfg.OutputPath == "" {
		return 0, 0, errors.New("OutputPath empty")
	}
	dir := filepath.Dir(m.cfg.OutputPath)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return 0, 0, fmt.Errorf("mkdir %s: %w", dir, err)
	}
	tmp, err := os.CreateTemp(dir, ".threatintel-*.tmp")
	if err != nil {
		return 0, 0, err
	}
	tmpName := tmp.Name()
	bw := bufio.NewWriter(tmp)
	header := fmt.Sprintf("# generated by latentguard threatintel at %s; %d entries\n",
		time.Now().UTC().Format(time.RFC3339), len(cidrs))
	written, _ := bw.WriteString(header)
	for _, c := range cidrs {
		n, _ := bw.WriteString(c + "\n")
		written += n
	}
	if err := bw.Flush(); err != nil {
		tmp.Close()
		os.Remove(tmpName)
		return 0, 0, err
	}
	if err := tmp.Close(); err != nil {
		os.Remove(tmpName)
		return 0, 0, err
	}
	if err := os.Rename(tmpName, m.cfg.OutputPath); err != nil {
		os.Remove(tmpName)
		return 0, 0, fmt.Errorf("rename: %w", err)
	}
	return len(cidrs), written, nil
}
