"""Promote approved rules to disk + trigger Coraza hot-reload.

The proxy mounts a shared volume at $LG_GENERATED_RULES_DIR (default
/etc/coraza/rules/lg-generated/). On promote/expire we rewrite the
whole directory from rules_queue (state in Mongo is the source of
truth -- the disk files are a projection) and POST to the proxy
/__reload endpoint with a bearer token from JWT_SECRET so Coraza
re-parses the live rule set.

Why rewrite the whole directory rather than per-file diffs: easier
to reason about, cheap (handful of files), and guarantees disk
matches Mongo even after a partial failure. The hot path is
unaffected -- promotion is operator-triggered.
"""
from __future__ import annotations

import logging
import os
import time
from pathlib import Path
from typing import Any

import httpx

from .store import RuleStatus, list_rules, mark_promoted

logger = logging.getLogger("latentguard.ml.rulegen.promoter")


def generated_dir() -> Path:
    raw = os.environ.get("LG_GENERATED_RULES_DIR", "/etc/coraza/rules/lg-generated")
    p = Path(raw)
    p.mkdir(parents=True, exist_ok=True)
    return p


def proxy_reload_url() -> str:
    return os.environ.get("PROXY_RELOAD_URL", "http://proxy:8080/__reload")


def _file_for_rule(rule_id: int) -> Path:
    return generated_dir() / f"lg-{rule_id}.conf"


def _write_live_rules() -> list[int]:
    """Rewrite the generated dir from rules with status=live. Returns rule_ids written."""
    target_dir = generated_dir()
    live = list_rules(status=RuleStatus.LIVE, limit=10_000)
    wanted = {int(r["rule_id"]): r for r in live}

    # Remove .conf files for rules no longer live.
    for existing in target_dir.glob("lg-*.conf"):
        try:
            stem = existing.stem  # lg-NNNNNN
            rid = int(stem.split("-", 1)[1])
        except (ValueError, IndexError):
            continue
        if rid not in wanted:
            try:
                existing.unlink()
                logger.info("promoter: removed %s", existing)
            except OSError as exc:
                logger.warning("promoter: failed to remove %s: %s", existing, exc)

    written: list[int] = []
    for rid, rule in wanted.items():
        path = _file_for_rule(rid)
        text = rule.get("rule_text") or ""
        if not text.endswith("\n"):
            text += "\n"
        header = (
            f"# Auto-generated by LatentGuard M9 orchestrator.\n"
            f"# rule_id={rid} provider={rule.get('provider')} "
            f"approved_by={rule.get('approved_by')}\n"
            f"# DO NOT EDIT BY HAND -- changes will be overwritten on next promote.\n"
        )
        path.write_text(header + text, encoding="utf-8")
        written.append(rid)
    return written


def _trigger_proxy_reload() -> dict[str, Any]:
    url = proxy_reload_url()
    # Issue a service token from the same JWT secret so the proxy verifier
    # accepts us. Using the auth module's issue_token keeps the signing path
    # identical to user logins.
    from ..auth import issue_token
    token, _exp = issue_token("ml-service")
    started = time.time()
    try:
        resp = httpx.post(
            url,
            headers={"Authorization": f"Bearer {token}"},
            timeout=10.0,
        )
        ok = resp.status_code < 400
        return {
            "ok": ok,
            "status_code": resp.status_code,
            "elapsed_ms": int((time.time() - started) * 1000),
            "body": resp.text[:200],
        }
    except httpx.HTTPError as exc:
        return {"ok": False, "error": str(exc), "elapsed_ms": int((time.time() - started) * 1000)}


def promote_approved() -> dict[str, Any]:
    """Flip approved rules to live, sync disk, reload proxy."""
    from .store import _transition  # transition helper does state checks
    approved = list_rules(status=RuleStatus.APPROVED, limit=1000)
    flipped: list[int] = []
    for r in approved:
        rid = int(r["rule_id"])
        try:
            _transition(rid, RuleStatus.LIVE, actor="promoter", note="auto-promote on approve")
            flipped.append(rid)
        except (KeyError, ValueError) as exc:
            logger.warning("promoter: skip rule %s: %s", rid, exc)
    written = _write_live_rules()
    for rid in written:
        mark_promoted(rid)
    reload_result = _trigger_proxy_reload()
    return {
        "ok": reload_result.get("ok", False),
        "flipped_to_live": flipped,
        "written_files": written,
        "reload": reload_result,
    }


def remove_expired() -> dict[str, Any]:
    """Sync disk after expiring rules (rules_queue must already be updated)."""
    written = _write_live_rules()
    reload_result = _trigger_proxy_reload()
    return {
        "ok": reload_result.get("ok", False),
        "live_after": written,
        "reload": reload_result,
    }
